### ISSUE TITLE
401 "error":"authorization failed" client side

### ISSUE THREAD

**Issue by b4b857f6ee** [ratibor78/geostat#8]
Hello,

On Ubuntu with nginx, a working telegraf and i use the same credentials for your settings as my telegraf.conf file, i get this : 

root@SRV:/opt/geostat# /opt/geostat/venv/bin/python geoparser.py
Traceback (most recent call last):
  File "geoparser.py", line 101, in <module>
    main()
  File "geoparser.py", line 94, in main
    logparse(LOGPATH, INFLUXHOST, INFLUXPORT, INFLUXDBDB, INFLUXUSER, INFLUXUSERPASS, MEASUREMENT, GEOIPDB, INODE) # NOQA
  File "geoparser.py", line 69, in logparse
    CLIENT.write_points(METRICS)
  File "/opt/geostat/venv/local/lib/python2.7/site-packages/influxdb/client.py", line 490, in write_points
    tags=tags, protocol=protocol)
  File "/opt/geostat/venv/local/lib/python2.7/site-packages/influxdb/client.py", line 551, in _write_points
    protocol=protocol
  File "/opt/geostat/venv/local/lib/python2.7/site-packages/influxdb/client.py", line 327, in write
    headers=headers
  File "/opt/geostat/venv/local/lib/python2.7/site-packages/influxdb/client.py", line 286, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 401: {"error":"authorization failed"}

but my account for influxdb setting.ini is the same as my telegraf configuration who is already work. any idea?

**Comment by ratibor78** [comment]
@b4b857f6ee Do you fix this or you're still experiencing the same issue?

**Comment by ratibor78** [comment]
For me, it looks like you need to check the settings.ini file and check the InfluxDB credentials, also mind that this version of the program doesn't supply the SSL connection to the InfluxDB for now.

**Comment by b4b857f6ee** [comment]
> 
> 
> For me, it looks like you need to check the settings.ini file and check the InfluxDB credentials, also mind that this version of the program doesn't supply the SSL connection to the InfluxDB for now.

I think i fix it, i don't remember, let me check to night.

**Comment by ratibor78** [comment]
There was a newly reworked version of the application published, I will close this issue, we can reopen it if it'll be needed.
